# Generated by Django 3.2.8 on 2022-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalSummary',
            new_name='patientmedicalsummary',
        ),
    ]
