# Generated by Django 3.2.8 on 2022-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstApp', '0004_delete_medicalsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalsummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_item', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=50)),
                ('strength_concentration', models.FloatField()),
                ('presentation', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('expire', models.DateField()),
                ('batch_id_timing', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('amount_unit', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
            ],
        ),
    ]
