# Generated by Django 3.2.8 on 2022-01-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
